#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry G4L {
	linux /bz3x9.6 ramdisk_size=131072 root=/dev/ram0 telnetd=yes
	initrd /ramdisk.lzma
}

